version: '3.1' # version ของ docker compose
services:

  php:
    build: ./docker-php 
    working_dir: /var/www/html 
    volumes:
      - ./opencart:/var/www/html:rw
    env_file: .env

  nginx:
    build: ./docker-nginx
    working_dir: /var/www/html 
    ports:
      - 8000:80 
    volumes:
      - ./opencart:/var/www/html:rw

  database:
    image: mariadb:10.2.16
    volumes:
      - ./mysql/data:/var/lib/mysql 
      - ./schema:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306" 

  adminer:
    image: adminer
    container_name: docker_adminer
    privileged: true
    restart: always
    env_file: .env
    ports:
      - "4444:8080"
